title: Hola.
description: 'My name is Jamie Fehr. I am happily married in Malaga,  Spain.'
messenger_url: https://m.me/videomonkey43
google_analytics:
theme: jekyll-theme-minimal
timezone: Europe/Madrid
email: jamiefehr@fastmail.es
baseurl: 
url: https://hola.fgvl.co
twitter_username: videomonkey
github_username: videomonkey
bitbucket_username: videomonkey
markdown: kramdown
plugins:
- jekyll-feed
