---
title: Hola.
timezone: Europe/Madrid
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: james@fgvl.co
description: 'My name is Jamie Fehr. I care a lot about Christ, health and technology.
  I live in Malaga,  Spain. Check out my twitter, youtube, flickr and facebook. '
baseurl: 
url: https://hola.fgvl.co
twitter_username: videomonkey
github_username: videomonkey
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
