---
title: Hola.
timezone: Europe/Madrid
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: My name is Jamie Fehr. I am happily married in Malaga,  Spain.
theme: minima
email: jamiefehr@fastmail.es
baseurl: 
url: https://hola.fgvl.co
twitter_username: videomonkey
github_username: videomonkey
bitbucket_username: videomonkey
markdown: kramdown
plugins:
- jekyll-feed
